package com.hyper.music.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Bluetooth
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.MoreVert
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material.icons.filled.Loop
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.hyper.music.model.Playlist
import com.hyper.music.model.Song

@Composable
fun PlaylistScreen(
    playlist: Playlist,
    onSongClick: (Song) -> Unit,
    onEditClick: () -> Unit,
    onSongMoreClick: (Song) -> Unit,
    onDeleteSong: (Song) -> Unit,
    onEditSongInfo: (Song) -> Unit,
    onShareSong: (Song) -> Unit,
    onSetRingtoneSong: (Song) -> Unit
) {
    var expandedSongId by remember { mutableStateOf<String?>(null) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
    ) {
        // Playlist Header
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            if (playlist.imageRes != null) {
                Image(
                    painter = painterResource(id = playlist.imageRes),
                    contentDescription = "Playlist Art",
                    contentScale = ContentScale.Crop,
                    modifier = Modifier
                        .size(160.dp)
                        .clip(RoundedCornerShape(16.dp))
                )
            } else {
                Box(
                    modifier = Modifier
                        .size(160.dp)
                        .clip(RoundedCornerShape(16.dp))
                        .background(MaterialTheme.colorScheme.surfaceVariant),
                    contentAlignment = Alignment.Center
                ) {
                    Text("No Image")
                }
            }
            Spacer(modifier = Modifier.height(16.dp))
            Text(
                text = playlist.title,
                style = MaterialTheme.typography.headlineMedium,
                fontWeight = FontWeight.Bold
            )
            Text(
                text = "${playlist.songs.size} songs",
                style = MaterialTheme.typography.bodyLarge,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
            
            Spacer(modifier = Modifier.height(16.dp))
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.Center,
                verticalAlignment = Alignment.CenterVertically
            ) {
                FilledIconButton(onClick = { if(playlist.songs.isNotEmpty()) onSongClick(playlist.songs.first()) }) {
                    Icon(Icons.Default.PlayArrow, contentDescription = "Play")
                }
                Spacer(modifier = Modifier.width(16.dp))
                IconButton(onClick = { /* TODO */ }) {
                    Icon(Icons.Default.Bluetooth, contentDescription = "Bluetooth")
                }
                Spacer(modifier = Modifier.width(8.dp))
                IconButton(onClick = { /* TODO */ }) {
                    Icon(Icons.Default.Loop, contentDescription = "Loop")
                }
                if (!playlist.isAutoGenerated) {
                    Spacer(modifier = Modifier.width(8.dp))
                    IconButton(onClick = onEditClick) {
                        Icon(Icons.Default.Edit, contentDescription = "Edit Playlist")
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(8.dp))

        // Songs List
        LazyColumn(
            contentPadding = PaddingValues(start = 16.dp, end = 16.dp, bottom = 120.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            items(playlist.songs) { song ->
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier
                        .fillMaxWidth()
                        .clip(RoundedCornerShape(8.dp))
                        .clickable { onSongClick(song) }
                        .padding(vertical = 6.dp)
                ) {
                    Image(
                        painter = painterResource(id = song.imageRes),
                        contentDescription = "Album Art",
                        contentScale = ContentScale.Crop,
                        modifier = Modifier
                            .size(56.dp)
                            .clip(RoundedCornerShape(8.dp))
                    )
                    Spacer(modifier = Modifier.width(16.dp))
                    Column(modifier = Modifier.weight(1f)) {
                        Text(
                            text = song.title,
                            style = MaterialTheme.typography.bodyLarge,
                            fontWeight = FontWeight.SemiBold
                        )
                        Text(
                            text = song.artist,
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    Box {
                        IconButton(onClick = { expandedSongId = song.id }) {
                            Icon(Icons.Default.MoreVert, contentDescription = "Options")
                        }
                        SongOptionsDropdown(
                            expanded = expandedSongId == song.id,
                            onDismissRequest = { expandedSongId = null },
                            onEditInfo = { onEditSongInfo(song) },
                            onDelete = { onDeleteSong(song) },
                            onShare = { onShareSong(song) },
                            onSetRingtone = { onSetRingtoneSong(song) }
                        )
                    }
                }
            }
        }
    }
}
