package com.hyper.music.model

data class Song(
    val id: String,
    val title: String,
    val artist: String,
    val imageRes: Int? = null,
    val imageUri: String? = null,
    val dataUri: String? = null,
    val playCount: Int = 0,
    val isFavorite: Boolean = false,
    val durationMs: Long = 210000,
    val favoriteTimestamp: Long = 0
)

data class Playlist(
    val id: String,
    val title: String,
    val songs: List<Song>,
    val imageRes: Int? = null,
    val isAutoGenerated: Boolean = false
)
